"""remove the enum

Revision ID: 676f0f10d095
Revises: 913e68fe7a48
Create Date: 2026-02-03 16:31:09.090721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '676f0f10d095'
down_revision: Union[str, Sequence[str], None] = '913e68fe7a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'admin', name='role'),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('student', 'admin', name='role'),
               existing_nullable=True)
    # ### end Alembic commands ###
