"""index course_code

Revision ID: 8f4fcdcf25fc
Revises: 676f0f10d095
Create Date: 2026-02-05 10:46:17.260504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4fcdcf25fc'
down_revision: Union[str, Sequence[str], None] = '676f0f10d095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courses_course_code_key'), 'courses', type_='unique')
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.create_unique_constraint(op.f('courses_course_code_key'), 'courses', ['course_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
